# Generated by Django 3.0.2 on 2020-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='makan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='zaman',
            field=models.TextField(blank=True),
        ),
    ]
