# Generated by Django 3.0.2 on 2020-01-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200125_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer',
            new_name='user',
        ),
    ]
