# Generated by Django 3.0.2 on 2020-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200127_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
