# Generated by Django 3.0.2 on 2020-02-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastName',
        ),
    ]
