# Generated by Django 3.0.2 on 2020-02-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200206_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qrcode',
        ),
    ]
