# Generated by Django 3.0.2 on 2020-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_ticket_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
